version: '3.7'

services:
  web:
    build:
      context: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 
    expose:
      - 8000
    volumes:
      - static_volume:/app/django_starter/django_starter/static
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/django_starter/django_starter/static
    ports:
      - 80:80
    depends_on:
      - web
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=django_starter

volumes:
  postgres_data:
  static_volume:
